{% set name = "unittest-xml-reporting" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: edd8d3170b40c3a81b8cf910f46c6a304ae2847ec01036d02e9c0f9b85762d28

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - lxml

test:
  imports:
    - xmlrunner
    - xmlrunner.extra

about:
  home: http://github.com/xmlrunner/unittest-xml-reporting/tree/master/
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: unittest-based test runner with Ant/JUnit like XML reporting.
  doc_url: https://pypi.org/project/unittest-xml-reporting/
  dev_url: http://github.com/xmlrunner/unittest-xml-reporting

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
