{% set name = "unittest-xml-reporting" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bfa1ed65e9e6f33c161d04470d89050458cfb65a5a5d0358834ef7ce037d9136

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - xmlrunner
    - xmlrunner.extra

about:
  home: http://github.com/xmlrunner/unittest-xml-reporting/tree/master/
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: unittest-based test runner with Ant/JUnit like XML reporting.
  doc_url: https://pypi.org/project/unittest-xml-reporting/
  dev_url: http://github.com/xmlrunner/unittest-xml-reporting

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
